### PR TITLE
Downgrade compiler requirement from C++11 to C++0x, to enable compati…

### PR DESCRIPTION
**Pull request by hughperkins**
Downgrade compiler requirement from C++11 to C++0x, to enable compatibility with earlier versions of gcc, and with python 2.7 on Windows, and Python 3.4 on Windows

Addresses https://github.com/CNugteren/CLBlast/issues/33

### CODE REVIEW

**Comment by CNugteren** [comment]
Unless you have a specific compiler in mind for which this works, I will close this pull request. Tested myself with GCC 4.6 and that doesn't seem to work: it is missing too many C++11 features.

**Comment by hughperkins** [comment]
The specific compiler is: msvc 2008.  It's true that c++0x and msvc2008 are not terribly close though, so we could just look at ensuring that build on msvc2008 works.

**Comment by hughperkins** [comment]
(or: at least, msvc2010; and I can build for msvc2008 in another way)

**Comment by CNugteren** [comment]
Yeah, OK, but this single 'fix' doesn't actually fix compilation in Visual Studio 2008. So, I think we should continue this discussion in the other issue or PR related to actual changes to the code base. In that case, I would propose to try to go to Visual Studio 2013 first, since that one is already missing many many C++11 features (https://msdn.microsoft.com/en-us/library/hh567368.aspx). If that will ever work, we can go back in history one step at a time.

**Comment by hughperkins** [comment]
> So, I think we should continue this discussion in the other issue or PR related to actual changes to the code base.

Yes thats fine for me

> I would propose to try to go to Visual Studio 2013 first,

vs2013 doesnt really help me much: my goal is to build for python 2.7 or 3.4, wihch is msvc2008 and msvc2010.

I have submitted an initial PR for how the changes for msvc2008/2010 will look.  They're quite radical, so not sure how willing you would be to accept those?

**Pull request closed without merging**
