### PR TITLE
set the correct flop count for xgemm

### PR DESCRIPTION
**Pull request by JishinMaster**
Set the correct flop count for xgemm (especially cgemm and zgemm).
Related to #415

### CODE REVIEW

**Comment by CNugteren** [comment]
Thanks for your pull request. I think it looks good. One note however: did you check for other routines with a similar computation? I guess the tuners/clients for other level3/x operations might have a similar formula that needs updating (e.g. triangular matrix mutliplication or batched-gemm operations).

**Comment by JishinMaster** [comment]
I will look into it! :)

**Comment by JishinMaster** [comment]
I upgraded the flops of some level3 and levelx functions.
I used the OpenBLAS for the flops formula (https://github.com/xianyi/OpenBLAS/tree/develop/benchmark).
It seems it would need to be extended further than level3 (axpy for instance).

**Comment by CNugteren** [comment]
Thanks for your addition, looks good, let's merge it! The non-level-3 ops are typically measured in GB/s so that should not be an issue.

**Pull request merged**
