### PR TITLE
Adapt opencl files for 1.1 OpenCL

### PR DESCRIPTION
**Pull request by dvasschemacq**
In OpenCL 1.1 __kernel has to be before __attribute__, at least with
Vivante compiler.

### CODE REVIEW

**Comment by CNugteren** [comment]
Thanks, this change looks fine (as discussed in #88). However, can you make this pull request to the `development` branch instead? You'll have to re-create it unfortunately.

**Comment by bhack** [comment]
Is it still required? See https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by CNugteren** [comment]
I followed bhack's advice, but now the pull request is not as clean as before unfortunately. I'll have to merge it in later, probably tomorrow.

**Comment by dvasschemacq** [comment]
Ok, if we have another modification we will push it on the development branch next time. :)

No more action required from my side as I understand?

**Pull request merged**
