### PR TITLE
Ensure the clGetKernelWorkGroupInfo return value fits.

### PR DESCRIPTION
**Pull request by gcp**
In LocalMemUsage(), there's a first call to clGetKernelWorkGroupInfo to get the "bytes" amount needed to store the result from CL_KERNEL_LOCAL_MEM_SIZE. However, the actual value passed is an "auto result = size_t", which in 32-bit mode is 4 bytes, regardless of the previous return value. The spec describes that this is actually a cl_ulong which is 8 bytes. So at this point clGetKernelWorkGroupInfo will corrupt the stack because the passed variable can't actually contain the result it wants to write. 

Fixes issue #71

### CODE REVIEW

**Comment by CNugteren** [comment]
OK, thanks! That seems like a bug indeed, I haven't tested on 32-bit, so thanks for doing that. Two comments:

1. Instead of `cl_ulong result = size_t{0};` I would suggest `auto result = cl_ulong{0};` to make it a bit more understandable for the reader of the code and in line with the code style.
2. If the result is indeed an `unsigned long`, perhaps we should also return it from the function as that type. Now we could lose information by casting it to a `size_t`. But I guess it's fine because this shouldn't exceed the max for a 32-bit value anyways.

Could you fix point 1? And then also create a new pull request to merge it into the `development` branch instead of into `master`? Thanks! I can also fix it myself but this way your contribution will be official :-)

**Comment by gcp** [comment]
Sounds fine. I considered (2) initially but wasn't sure if I wanted to adjust all callers. But if you prefer that, I'll make that change too.

**Comment by CNugteren** [comment]
No, I guess just (1) is fine.

**Comment by gcp** [comment]
Looks like there's only a single user of the return value, receiving it into an "auto". That's then used to call another function...that has a cl_ulong and static_casts it to size_t to avoid a type mismatch. So (2) actually makes everything simpler :)

**Comment by gcp** [comment]
Looks like github doesn't allow changing the target of a pull request. Huh! I'll close and reopen for the development branch.

**Pull request closed without merging**
