### PR TITLE
Fix segfault on teardown

### PR DESCRIPTION
**Pull request by hughperkins**
- I get a segfault on teardown in tensorflow:
segfault_clblast_tensorflow

- I can reproduce outside of tensorflow, using the following script: https://github.com/hughperkins/cuda-on-cl/blob/master/test/cocl/testblas.cu
segfault_in_testscript
- to run this script:
   - install cuda-on-cl
   - from `build` directory, do `make run-testblas`
   - I agree it's probably not the simplest demo script. anyway...
- usnig this test script, I can get the folowing stack trace from the segfault:
```
#0  0x00007ffff589f8c0 in ?? ()
#1  0x00007ffff63581bc in clblast::Program::Program(clblast::Context const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(_cl_program**)#1}::operator()(_cl_program**) const (__closure=0xc591f0, 
    p=0xc41e80) at /home/ubuntu/git/cuda-on-cl/src/CLBlast/src/clpp11.hpp:321
#2  0x00007ffff6359e28 in std::_Sp_counted_deleter<_cl_program**, clblast::Program::Program(clblast::Context const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(_cl_program**)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (this=0xc591e0)
    at /usr/include/c++/5/bits/shared_ptr_base.h:466
#3  0x00007ffff6329aec in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0xc591e0) at /usr/include/c++/5/bits/shared_ptr_base.h:150
#4  0x00007ffff6329751 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0xc08c08, __in_chrg=<optimised out>)
    at /usr/include/c++/5/bits/shared_ptr_base.h:659
#5  0x00007ffff63294c4 in std::__shared_ptr<_cl_program*, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0xc08c00, __in_chrg=<optimised out>)
    at /usr/include/c++/5/bits/shared_ptr_base.h:925
#6  0x00007ffff63294e0 in std::shared_ptr<_cl_program*>::~shared_ptr (
    this=0xc08c00, __in_chrg=<optimised out>)
    at /usr/include/c++/5/bits/shared_ptr.h:93
#7  0x00007ffff63296fa in clblast::Program::~Program (this=0xc08c00, 
    __in_chrg=<optimised out>)
    at /home/ubuntu/git/cuda-on-cl/src/CLBlast/src/clpp11.hpp:315
#8  0x00007ffff6329726 in clblast::ProgramCache::~ProgramCache (this=0xc08c00, 
    __in_chrg=<optimised out>)
    at /home/ubuntu/git/cuda-on-cl/src/CLBlast/src/cache.hpp:49
#9  0x00007ffff632b080 in std::_Destroy<clblast::ProgramCache> (
    __pointer=0xc08c00) at /usr/include/c++/5/bits/stl_construct.h:93
#10 0x00007ffff632ae45 in std::_Destroy_aux<false>::__destroy<clblast::ProgramCache*> (__first=0xc08c00, __last=0xc08c70)
    at /usr/include/c++/5/bits/stl_construct.h:103
#11 0x00007ffff632ab70 in std::_Destroy<clblast::ProgramCache*> (
    __first=0xc08c00, __last=0xc08c70)
    at /usr/include/c++/5/bits/stl_construct.h:126
#12 0x00007ffff632a50d in std::_Destroy<clblast::ProgramCache*, clblast::ProgramCache> (__first=0xc08c00, __last=0xc08c70)
    at /usr/include/c++/5/bits/stl_construct.h:151
#13 0x00007ffff632b45b in std::vector<clblast::ProgramCache, std::allocator<clblast::ProgramCache> >::~vector (this=0x7ffff6687f30 <clblast::program_cache_>, 
    __in_chrg=<optimised out>) at /usr/include/c++/5/bits/stl_vector.h:424
#14 0x00007ffff6f6a36a in __cxa_finalize (d=0x7ffff6686fe0)
    at cxa_finalize.c:56
#15 0x00007ffff6265913 in __do_global_dtors_aux ()
---Type <return> to continue, or q <return> to quit---q
 from /home/ubuntu/git/cuda-onQuit
```
- the changes in this PR make htis segfault go away :-)
nosegfault_clblast_tensorflow

### CODE REVIEW

**Comment by hughperkins** [comment]
(oh wait, the script to reproduce the segfault outside of tensorflow hadnt been pushed to github yet, it is here:
https://github.com/hughperkins/cuda-on-cl/blob/10887704145a9f8dcebc58df5c679cd98cc9e1f0/test/cocl/testblas.cu  (basically commented out the `cublasDestroy(blas)`, which means that clear cache is no longer called:
https://github.com/hughperkins/cuda-on-cl/blob/10887704145a9f8dcebc58df5c679cd98cc9e1f0/src/cocl_blas.cpp#L58
)

**Comment by CNugteren** [comment]
So, you are really just proposing to remove cleaning-up `cl_program`? So your whole PR could be reduced to changing:
```
program_(new cl_program, [](cl_program* p) { CheckError(clReleaseProgram(*p)); delete p; }),
```
into
```
program_(new cl_program, [](cl_program* p) { delete p; }),
```
Am I right to say this has the same effect - could you confirm this for me?

That said, why do you think we shouldn't release the program? Perhaps we should investigate what else is going on, because with your PR we'll introduce memory leaks. Have you tested on a different system? Tried different drivers and SDK?

**Comment by hughperkins** [comment]
Agree with your analysis. Concur with your observation. My own priority is to remove the segfault, but I imagine some cleaner solution might be possible?

On 26 November 2016 08:57:31 GMT+00:00, Cedric Nugteren <notifications@github.com> wrote:
>So, you are really just proposing to remove cleaning-up `cl_program`?
>So your whole PR could be reduced to changing:
>```
>program_(new cl_program, [](cl_program* p) {
>CheckError(clReleaseProgram(*p)); delete p; }),
>```
>into
>```
>program_(new cl_program, [](cl_program* p) { delete p; }),
>```
>Am I right to say this has the same effect - could you confirm this for
>me?
>
>That said, why do you think we shouldn't release the program? Perhaps
>we should investigate what else is going on, because with your PR we'll
>introduce memory leaks. Have you tested on a different system? Tried
>different drivers and SDK?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/CNugteren/CLBlast/pull/126#issuecomment-263052398

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by CNugteren** [comment]
Can you tell me what OS you are on? And which OpenCL device and drivers are you testing on?

It would be nice to have a plain C/C++ test program to eliminate the dependencies for this issue and to ensure that the bug is really caused by CLBlast. Can you make such a program for me so that I can try to reproduce it?

**Comment by hughperkins** [comment]
> It would be nice to have a plain C/C++ test program to eliminate the dependencies for this issue and to ensure that the bug is really caused by CLBlast. 

Yeah, thats fair enough :-)  Let me see if I can come up with something.  But, to answer your earlire question, I've tested on:
- ubuntu 16.04 + nvidia k520
- ubuntu 16.04 + nvidia 940m
- ubuntu 16.04 + Intel hd5500 + beignet 1.2.1

I can fix the issue by clearing the cache prior to the end of the program, but it's not obvious how to trigger this during tensorflow shutdown.

My hypothesis is that the programs are being deleted/released after the cl context has already long died.

**Comment by hughperkins** [comment]
Oh, one piece of informatoin; all buffers are carved out of the same, huge, cl_mem, rather than individual cl_mem per tensor.

**Comment by hughperkins** [comment]
Hmmm, well, a simple sample does work ok in fact, ie 
```

// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. This
// project loosely follows the Google C++ styleguide and uses a tab-size of two spaces and a max-
// width of 100 characters per line.
//
// Author(s):
//   Cedric Nugteren <www.cedricnugteren.nl>
//
// This file demonstrates the use of the SGEMM routine. It is pure C99 and demonstrates the use of
// the C API to the CLBlast library.
//
// Note that this example is meant for illustration purposes only. CLBlast provides other programs
// for performance benchmarking ('client_xxxxx') and for correctness testing ('test_xxxxx').
//
// =================================================================================================

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

// Includes the CLBlast library (C interface)
#include <clblast_c.h>

// =================================================================================================

// Example use of the single-precision routine SGEMM
int main(void) {

  // OpenCL platform/device settings
  const size_t platform_id = 0;
  const size_t device_id = 0;

  // Example SGEMM arguments
  const size_t m = 128;
  const size_t n = 64;
  const size_t k = 512;
  const float alpha = 0.7f;
  const float beta = 1.0f;
  const size_t a_ld = m;
  const size_t b_ld = k;
  const size_t c_ld = m;

    int A_offset = 256;
    int B_offset = A_offset + 2 * m * k * sizeof(float);
    int C_offset = B_offset + 2 * n * k * sizeof(float);
  printf("a offset %i b offset %i c offset %i\n", A_offset, B_offset, C_offset);

  // Initializes the OpenCL platform
  cl_uint num_platforms;
  clGetPlatformIDs(0, NULL, &num_platforms);
  cl_platform_id* platforms = (cl_platform_id*)malloc(num_platforms*sizeof(cl_platform_id));
  clGetPlatformIDs(num_platforms, platforms, NULL);
  cl_platform_id platform = platforms[platform_id];

  // Initializes the OpenCL device
  cl_uint num_devices;
  clGetDeviceIDs(platform, CL_DEVICE_TYPE_ALL, 0, NULL, &num_devices);
  cl_device_id* devices = (cl_device_id*)malloc(num_devices*sizeof(cl_device_id));
  clGetDeviceIDs(platform, CL_DEVICE_TYPE_ALL, num_devices, devices, NULL);
  cl_device_id device = devices[device_id];

  // Creates the OpenCL context, queue, and an event
  cl_context context = clCreateContext(NULL, 1, &device, NULL, NULL, NULL);
  cl_command_queue queue = clCreateCommandQueue(context, device, 0, NULL);
  // cl_event event = NULL;

  // Populate host matrices with some example data
  float* host_a = (float*)malloc(sizeof(float)*m*k);
  float* host_b = (float*)malloc(sizeof(float)*n*k);
  float* host_c = (float*)malloc(sizeof(float)*m*n);
  for (size_t i=0; i<m*k; ++i) { host_a[i] = 12.193f; }
  for (size_t i=0; i<n*k; ++i) { host_b[i] = -8.199f; }
  for (size_t i=0; i<m*n; ++i) { host_c[i] = 0.0f; }

  // Copy the matrices to the device
  cl_mem device_big = clCreateBuffer(context, CL_MEM_READ_WRITE, 64 * 1024 * 1024, NULL, NULL);
  // cl_mem device_b = clCreateBuffer(context, CL_MEM_READ_WRITE, n*k*sizeof(float), NULL, NULL);
  // cl_mem device_c = clCreateBuffer(context, CL_MEM_READ_WRITE, m*n*sizeof(float), NULL, NULL);
  clEnqueueWriteBuffer(queue, device_big, CL_TRUE, A_offset, m*k*sizeof(float), host_a, 0, NULL, NULL);
  clEnqueueWriteBuffer(queue, device_big, CL_TRUE, B_offset, n*k*sizeof(float), host_b, 0, NULL, NULL);
  clEnqueueWriteBuffer(queue, device_big, CL_TRUE, C_offset, m*n*sizeof(float), host_c, 0, NULL, NULL);

  // Call the SGEMM routine.
  StatusCode status = CLBlastSgemm(kColMajor, kNo, kNo,
                                   m, n, k,
                                   alpha,
                                   device_big, A_offset >> 2, a_ld,
                                   device_big, B_offset >> 2, b_ld,
                                   beta,
                                   device_big, C_offset >> 2, c_ld,
                                   &queue, 0);

  clEnqueueReadBuffer(queue, device_big, CL_TRUE, A_offset, m*k*sizeof(float), host_a, 0, NULL, NULL);
  clEnqueueReadBuffer(queue, device_big, CL_TRUE, B_offset, n*k*sizeof(float), host_b, 0, NULL, NULL);
  clEnqueueReadBuffer(queue, device_big, CL_TRUE, C_offset, m*n*sizeof(float), host_c, 0, NULL, NULL);

  // Wait for completion
  // clWaitForEvents(1, &event);
  // clReleaseEvent(event);
  clFinish(queue);

  // Example completed. See "clblast_c.h" for status codes (0 -> success).
  printf("Completed SGEMM with status %d\n", status);

  // Clean-up
  free(platforms);
  free(devices);
  free(host_a);
  free(host_b);
  free(host_c);
  clReleaseMemObject(device_big);
  // clReleaseMemObject(device_b);
  // clReleaseMemObject(device_c);
  clReleaseCommandQueue(queue);
  clReleaseContext(context);
  return 0;
}

// =================================================================================================
```
I should probably dig a bit...

**Comment by hughperkins** [comment]
I'll close this until I have a test case I can demonstrate...

**Comment by hughperkins** [comment]
(My current hypothesis is that it's because I'm not using your cmakelists, and the compile options I'm using, which come from llvm options, interfere with something somehow.  for example, rtti is off, and lots of werid things like that.  I switched to building clblast directly from my own cmakelists at about the time I switched to building statically.  But I might switch back.  Or, at least, test this hypothesis)

**Comment by CNugteren** [comment]
In that case I would suggest compiling CLBlast separately or even using the binaries. I've just made a new release (version 0.10.0 - master branch is updated) which brings some improvements as well.

**Pull request closed without merging**
