### PR TITLE
Convert to use C++ exceptions internally

### PR DESCRIPTION
**Pull request by intelfx**
Refactor the whole codebase to only use C++ exceptions internally instead of endlessly nesting try-catch expressions against exceptions thrown from the OpenCL C++ wrapper.

Given that the code is already uses proper C++ idioms, it's easier to just use exceptions internally. Instead, the exceptions are now caught at the top level only and converted to status codes to preserve the existing library API.

Note that we deliberately do not catch C++ runtime errors (such as `std::bad_alloc`) nor logic errors (aka failed assertions) in the C++ API because no actual handling can ever happen for such errors.

However, in the C interface wrapper _all_ exceptions (even unknown ones) are caught and converted to the "catch-all" `kUnexpectedError` code.

Related to issue #110.

### CODE REVIEW

**Comment by CNugteren** [comment]
First of all thanks for the work!

It is a long list of changes so it took me some time to go through everything. Of course many are just small changes that show up like large changes (e.g. un-indenting a whole function). In general I am quite happy with the changes and I think it improves the library a lot.

There is one thing do that I would like to ask you to change if possible. This concerns the `clpp11.hpp` file. This is part of https://github.com/CNugteren/CLCudaAPI and is thus meant to be independent of CLBlast and single-header only. Right now this changed due to the new exception class. Would it be possible to make the header stand-alone again, keeping in mind that all changes will have to be made (and should be possible to make) in the CUDA version of the CLCudaAPI header? I hope this is not to difficult to achieve. I can also help if you want.

**Comment by CNugteren** [comment]
Indeed, those two options are not so nice. Can we not have a simple exception class in `clpp11.h` that handles all exceptions from OpenCL functions? Or does it really need to inherit from the same base exception class that the other CLBlast exceptions use?

**Comment by intelfx** [comment]
@CNugteren 

I ended up not using inheritance for anything other than just reducing amount of boilerplate code[1]. So, in some sense, it doesn't. However, there are three types of exceptions thrown from there (not just one).

[1]: which is not really nice, but I could not invent a good "semantic" inheritance design. Probably not worth the effort, though.

**Comment by intelfx** [comment]
I could suggest playing a deadly linker dance with weak functions, but that's not portable to MSVC.

**Comment by CNugteren** [comment]
No, let's not do any kind of dances. Perhaps I should just merge it in and see if I can later make this compatible again with the idea of CLCudaAPI and a single interchangeable header for OpenCL / CUDA.

I'll go over the code one more time tomorrow and test it on my machines and then I'll merge it in. Thanks!

**Comment by intelfx** [comment]
Well, probably, I could simplify the exception class hierarchy, leaving only `CLError` used in the CL wrapper header. That way, we'll lose a bit of error code granularity... I'll attempt to do something overnight.

**Comment by CNugteren** [comment]
Yes, perhaps only a `CLError` for all errors in CLCudaAPI's abstraction of OpenCL would make sense.

**Comment by intelfx** [comment]
I mean, the other errors would go into the standard exception classes. This way we'll have to invent a single StatusCode for all non-CL errors reported from the CL header.

**Comment by intelfx** [comment]
...So, I'm afraid, this won't fly (at least strictly as discussed).

In the code I rely on the ability to catch "any runtime error generated by our code" (but exclude e.g. logic errors and C++ runtime errors). This means I have to move all three classes (`Error<Base>`, `ErrorCode<Base, Status>` and `CLError`) into the `clpp11.hpp` header.

While it's technically possible to create a completely separate exception class for CL errors, that would cost us code bloat in several places (in CLBlast). On the other hand, doing as outlined above would mean that we have to replicate the class hierarchy in the second (CUDA) implementation of CLCudaAPI.

I'd rather propose to forgo the "single file header" requirement and move the exception classes into a separate file, say, `cmpp11.hpp` (from "common") that will be common to CL and CUDA implementations of CLCudaAPI.

**Comment by intelfx** [comment]
> Also, I just got the request in #119 to add a prefix for the plain C version of the API. Can this be done easily in the current set-up with a #define or something? If not then perhaps we should split up the error codes again and move them to the 2 respective files. Perhaps it's nice as well to have everything in 1 single header, even if that means code duplication.

Ah, OK.

**Comment by intelfx** [comment]
(Probably) all done, please take a look.

**Comment by CNugteren** [comment]
Thanks again for all your effort! The new version looks good, I've tested in on two system myself as well. I've also added some of the error statuscodes mentioned above.

**Comment by CNugteren** [comment]
Just one more remark. I was testing the new code with MSVC today and noticed the following kind of errors:

```
C:\projects\clblast\src\utilities/clblast_exceptions.hpp(33): warning C4275: non dll-interface class 'clblast::RuntimeError' used as base for dll-interface class 'clblast::ErrorCode<clblast::RuntimeError,clblast::StatusCode>'
c:\projects\clblast\src\cxpp11_common.hpp(52): note: see declaration of 'clblast::RuntimeError'
C:\projects\clblast\src\utilities/clblast_exceptions.hpp(33): note: see declaration of 'clblast::ErrorCode<clblast::RuntimeError,clblast::StatusCode>'
C:\projects\clblast\src\utilities/clblast_exceptions.hpp(33): warning C4251: 'clblast::ErrorCode<clblast::RuntimeError,clblast::StatusCode>::details_': class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' needs to have dll-interface to be used by clients of class 'clblast::ErrorCode<clblast::RuntimeError,clblast::StatusCode>'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xstring(2633): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
```

So is it really necessary to make these exceptions part of the interface of the library? Aren't they all catched or converted to standard C++ exceptions? And if they are: how severe is this warning message and how do we prevent it from happening?

**Comment by intelfx** [comment]
I've simply forgot to remove `PUBLIC_API` attributes from the internally used exception classes (they are a left-over from my first attempt, when I still thought that they will be a public API). Try to remove the attributes from classes in `src/utilities/clblast_exceptions.hpp` and see if errors disappear.

Regarding your API worries: as I have said earlier, I deliberately do not catch "logic error" exceptions, because they cannot be handled in any meaningful way. However, all of our exception classes inherit from the default ones, so (to the best of my knowledge) they need not to be public/exported even if we do throw them across shared object boundaries.

(However, if you want, we can catch them too — I thought that there were no objections to this part.)

**Comment by CNugteren** [comment]
OK, that's clear. I've removed `PUBLIC_API` in two occurrences.

**Comment by psyhtest** [comment]
@intelfx Great work!

**Comment by intelfx** [comment]
@psyhtest This is actually a kind of "groundwork" for the plugin system (for which I'm writing an RFC/discussion issue right now). Considering the issues with linkage to our Mali GEMM overlay library on the devboard (and also keeping in mind the risk of ABI incompatibilities), I now think that overlaying symbols (either via linkage or LD_PRELOAD) isn't really a good approach.

**Comment by psyhtest** [comment]
@intelfx Excellent. Look forward to discussions on the plugin system!

**Pull request merged**
